<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
$_config      = $this->helper('Sm\Themecore\Helper\Data');
$_config_sm   = $this->helper('Sm\Xtore\Helper\Data');
$productStyle = $_config_sm->getThemeLayout('product_style');

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= /* @escapeNotVerified */
            __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode         = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription  = false;
        $templateType     = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode         = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription  = true;
        $templateType     = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    /*$pos    = $block->getPositioned();*/
	$pos = !empty($block->getPositioned()) ? $block->getPositioned() : '';
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */
    $viewMode ?> products-<?= /* @escapeNotVerified */
    $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */
                    $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <div class="image-product">
                            <a href="<?= /* @escapeNotVerified */
                            $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>

                            <?= $_config->getLabelProduct($_product); ?>
                        </div>

                        <div class="product details product-item-details">
							
							<?php /* getlist-category */
							if ($productStyle == 'product-2') {
								$objectManager = \Magento\Framework\App\ObjectManager::getInstance();    
								$product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
								$cat       = $product->getCategoryCollection()->addAttributeToSelect('*');
								$lastcat = count($cat);
								$i=0;
								foreach ($cat as $category) :
								  $i++;
								  if($i==$lastcat):
									  
							?>
									<div class="name-category">
									  <a href="<?php echo $category->getUrl();  ?>" class="cat-title" title="<?php echo $category->getName(); ?>">
										<?php echo $category->getName(); ?>
									  </a>
									</div>
							<?php   
									endif;
								endforeach;
							}
							?>
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */
                                   $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
							
							<?= $block->getReviewsSummaryHtml($_product, $templateType,true) ?>
                          
                            <?= $block->getProductDetailsHtml($_product) ?>

                            <?php if ($showDescription): ?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */
                                    $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */
                                    $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */
                                    $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */
                                        __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
							  <?= /* @escapeNotVerified */
                            $block->getProductPrice($_product) ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                  action="<?= /* @NoEscape */
                                                  $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product"
                                                       value="<?= /* @escapeNotVerified */
                                                       $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */
                                                Action::PARAM_NAME_URL_ENCODED ?>"
                                                       value="<?= /* @escapeNotVerified */
                                                       $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */
                                                        __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */
                                                        __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                        __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links"
                                         class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */
            $_product->getSku() ?>"
                }
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>
