<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="footer-style-1">
	<div class="footer-top">
        <div class="container">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-content')->toHtml(); ?>
        </div>
	</div>
	<div class="footer-bottom">
		<div class="container">
            <div class="row align-items-center">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                        <?php if ($_config->getAdvanced('copyright_group/custom_copyright')) { ?>
                            <address><?php echo $_config->getAdvanced('copyright_group/copyright_content') ?></address>
                        <?php } else { ?>
                            <address><?php echo $this->getChildHtml("copyright"); ?></address>
                        <?php } ?>
                    </div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-12">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
                    </div> 
            </div>
        </div>
    </div>
</div>
