<?php
/* @var $block \Magento\Sales\Block\Order\History\Container */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();

$resources = \Magento\Framework\App\ObjectManager::getInstance()
    ->get('Magento\Framework\App\ResourceConnection');
$connection= $resources->getConnection();

$incrementId = $this->getOrder()->getIncrementId();

$sql = "SELECT * FROM order_payment_proof WHERE increment_id='{$incrementId}'";
$result = $connection->fetchAll($sql);
?>
<td class="col slip">
    <?php if ($result): ?>
        <?php foreach ($result as $v): ?>
            <p>
                <a target="_blank" href="/pub/media<?php echo $v['file_path']; ?>">view slip</a>
                / date: <?php echo date('d M Y H:i:s', strtotime($v['created_date'])); ?>
            </p>
        <?php endforeach; ?>
    <?php endif; ?>
</td>
<td class="col slip">
    <a target="_blank" href="<?= $baseUrl.'fulloop_orders/slip/form/?order_id='.$this->getOrder()->getIncrementId() ?>">แจ้งชำระเงิน</a>
</td>
