<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
$_post     = $this->getPost();
$_postUrl  = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder  post-holder-<?php echo $_post->getId() ?>">
    <div class="post-content post-custom">
        <div class="post-description clearfix">
            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                <div class="post-ftimg-hld">
                    <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                        <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>"/>
                    </a>
					<div class="date-post">
						<?php
							$date_post = $_post->getPublishDate('F d, Y');
							$day       = date('d', strtotime($date_post));
							$month     = date('M', strtotime($date_post));
						?>
						<div class="day"><?php echo $day; ?></div>
						 <div class="month"><?php echo $month; ?></div> 
					</div>
                </div>
            <?php } ?>

            <div class="post-info-blog">

                <div class="post-header">
                    <div class="post-title-holder clearfix">
                        <h2 class="post-title">
                            <a class="post-item-link"
                               href="<?php echo $_postUrl ?>">
                                <?php echo $_postName; ?>
                            </a>
                        </h2>
                    </div>
                </div>

               <div class="post-text-hld clearfix">
                    <?php echo $block->getShorContent() ?>
                </div>
				<div class="post-read-more">
                    <a href="<?php echo $_postUrl ?>"
                                   title="<?php echo $_postName ?>"><?php echo __('Read more') ?></a>
                </div>
                
            </div>

        </div>
    </div>
    <div class="post-footer">

    </div>
</li>
