/**
* Home page 1
*/
.slidershow .slidershow-type-1 .owl-dots .owl-dot:hover, 
.slidershow .slidershow-type-1 .owl-dots .owl-dot.active,
{ 
	color: #<?php echo $themeColor; ?>;
}
.slidershow .slidershow-type-1 .owl-nav [class*='owl-']:hover,
.title-style-1 .owl-theme .owl-nav [class*='owl-']:hover{ 
	background-color: #<?php echo $themeColor; ?>;
}
.quicklink ul > li > a:hover {
	border-color: #<?php echo $themeColor; ?>;
}

.sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li.tab-sel  span ,
.sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li:hover span{
	color: #<?php echo $themeColor; ?>;
}
.block-slider-products .block-filterproducts .block-content .deals-countdown{
	background-color: #<?php echo $themeColor; ?>;	
}
.block-slider-products .block-filterproducts .block-content .deals-countdown .num-time{ 
	color: #<?php echo $themeColor; ?>;	 	
}
.block-slider-products .block-filterproducts .block-content{
	border-color: #<?php echo $themeColor; ?>;	
}
.nav-style-1.absolute-nav .owl-theme .owl-nav [class*="owl-"]:hover{
	color: #<?php echo $themeColor; ?> !important;
}
.w-newsletter .action-newsletter button{
	background-color: #<?php echo $themeColor; ?>;
}
.social-popup ul li a:hover {
	background-color: #<?php echo $themeColor; ?>;
	border-color: #<?php echo $themeColor; ?>;  
}
.title-style-1 .block-title strong span {color: #<?php echo $themeColor2; ?>; }
.block-list-categories .block-categories-3 .block-content .cat-wrap .item .cats-info .child-cat ul.sub-cats li a:hover {
	color: #<?php echo $themeColor; ?>;  
}
.block-list-categories .block-categories-3 .block-content .cat-wrap .item .cats-info .child-cat ul.sub-cats li a:before{
	background-color: #<?php echo $themeColor; ?>;  
}
.block-list-categories .block-categories-3 .block-content .cat-wrap .item .image-cat .view-more:hover{
	background-color: #<?php echo $themeColor; ?>;  
	color:#fff;
}
.block-testimonials .block-content .item .info .client-name{
	color: #<?php echo $themeColor2; ?>;  
}

.owl-theme .owl-dots .owl-dot.active span, .owl-theme .owl-dots .owl-dot:hover span{
	background-color: #<?php echo $themeColor; ?>;  
}
