/**
* Header 1
*/

.header-style-1.header-container .search-container .popup-search .close-search:hover:before,
.header-style-1.header-container .search-container .popup-search .block-search .actions .action.search:hover:before,
.cms-index-index .horizontal-block .horizontal-menu .horizontal-megamenu-block .sm_megamenu_menu > li.home-item > a,
.header-style-1 .horizontal-block .horizontal-menu .horizontal-megamenu-block .sm_megamenu_menu > li.sm_megamenu_actived > a,
.horizontal-block .horizontal-menu .horizontal-megamenu-block .sm_megamenu_menu > li > a:hover{
	color: #<?php echo $themeColor2; ?>;
}

.vertical-menu-block .vertical-menu-content .more-w .more-view:hover {
	color: #<?php echo $themeColor; ?>;
}
.header-style-1.header-container .header-links ul li a:hover {
	color: #<?php echo $themeColor; ?>;
	
}
.header-style-1.header-container .search-container .block-search .actions .action.search{
	background-color: #<?php echo $themeColor2; ?>;
}
.header-style-1.header-container .search-container .block-search .actions .action.search:hover{
	background-color: #<?php echo $themeColor; ?>;
}
.header-style-1.header-container .language-currency .list-item a:hover {
	border-color: #<?php echo $themeColor; ?>;
}
.header-style-1 .header-bottom .menu-left.vertical_menu .vertical-menu-block .block-title-menu {
	background-color: #<?php echo $themeColor; ?>;
}
.menu-left.vertical_menu .vertical-menu-block .block-title-menu:before{
	background-color: #<?php echo $themeColor3; ?>;
}
.link_deal > a:hover{
	color: #<?php echo $themeColor2; ?>;
}
.header-content-right > div:hover { 
	background-color: #<?php echo $themeColor; ?>;
}
.desktop-menu .vertical-menu-block .vertical-menu-content .navigation > ul > li > a:hover,
.desktop-menu .vertical-menu-block .vertical-menu-content .navigation > ul li ul a:hover{
	color: #<?php echo $themeColor; ?>;
	
}

.header-content-right .customer-links ul.header.links li a:hover {
	border-color: #<?php echo $themeColor; ?>;
	color: #000;
}

.minicart-wrapper .block-minicart .block-content > .actions > .primary .action.primary,
.minicart-wrapper .block-minicart .block-content > .actions .secondary a:hover{
	background-color: #<?php echo $themeColor; ?>;
	opacity: 1;
}
.minicart-wrapper .block-minicart .block-content > .actions > .primary .action.primary:hover {
	background-color: #<?php echo $themeColor1; ?>;
}
.header-container .minicart-wrapper .action.showcart .counter.qty .counter-number,
.header-content-right .block-wishlist span.count{
	background-color: #<?php echo $themeColor2; ?>;
	
}
