/**
* Footer 1
*/
.footer-block-newsletter {	
	background-color:#<?php echo $themeColor1; ?>;
}
.block-subscribe-footer .newsletter-content .action-button button {
	background-color:#<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.block-footer .content-footer ul li a:before {
	background-color:#<?php echo $themeColor; ?>;
}
.block-footer .content-footer ul li a:hover {
	color:#<?php echo $themeColor; ?>;
}

.footer-style-1 .social-footer ul li a:hover{
	background-color:#<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}

