/**
* Product 1
*/
.product-labels .product-label.sale-label{
	background-color: #<?php echo $themeColor2; ?> !important; 
}
.product-labels .product-label.new-label{
	background-color: #<?php echo $themeColor; ?> !important; 
}

.products-grid:not(.wishlist) .product-item-info .product-item-details .price-box .price{
	color: #<?php echo $themeColor2; ?>;  
}
.products-grid:not(.wishlist) .product-item-info:hover .image-product{
	border-color: #<?php echo $themeColor; ?> !important; 
}
.products-grid:not(.wishlist) .product-item-info .product-item-details .product-item-actions .actions-secondary .action:hover{
	background-color: #<?php echo $themeColor; ?> !important; 
	border-color: #<?php echo $themeColor; ?> !important; 
}
.products-grid:not(.wishlist) .product-item-info .product-item-details .product-item-actions .actions-primary .tocart:hover {
	background-color: #<?php echo $themeColor; ?> !important; 
}
.products-list .product-item .actions-primary button{
	background-color: #<?php echo $themeColor; ?> !important; 
}
.product-item .price-box .price{
	color: #<?php echo $themeColor2; ?>; 
}

.products-grid:not(.wishlist) .product-item-info .deals-countdown .deals-time {
	background-color: #<?php echo $themeColor; ?> !important; 
}

