<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?> <div class="header-container header-style-1">
  <div class="header-top">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-4 col-sm-6">
          <div class="language-currency"> <?php echo $this->getChildHtml("store_language"); ?> <?php echo $this->getChildHtml("currency"); ?> </div>
        </div>
        <div class="col-lg-4 d-none d-lg-block"> <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block-header-top')->toHtml(); ?> </div>
        <div class="col-lg-4 col-sm-6 d-none d-sm-block"> <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-links')->toHtml(); ?> </div>
      </div>
    </div>
  </div>
  <div class="header-bottom">
      <div class="header-content-top">
		<div class="container">
        <div class="row justify-content-between align-items-center">
			<div class="col-lg-3">
				<div class="logo-container"> <?php echo $this->getChildHtml("logo"); ?> </div>
			</div>
			<div class="col-lg-6">
				<div class="search-container search-header"> <?php echo $this->getChildHtml("topSearch"); ?> </div>
			</div>
			<div class="col-lg-3">
			  <div class="header-content-right">
				
				<div class="customer-links" data-move="customer-mobile"> <?php echo $this->getChildHtml("header.links"); ?> </div>
				<?php echo $this->getChildHtml("wishlist.header"); ?>
				<div class="minicart-header" data-move="minicart-mobile"> <?php echo $this->getChildHtml("minicart"); ?> </div>
			  </div>
			</div>
        </div>
      </div>
	</div>  
      <div class="header-content-bottom ontop-element desktop-menu ">
		<div class="container">
		<div class="d-flex">
        <div class="menu-left vertical_menu">
          <div class="vertical-block"> <?php
                    if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') { 
                        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-vertical')->toHtml();
                    } else {
                        echo $this->getChildHtml("vertical-css");
                    }
                    ?> </div>
        </div>
        <div class="horizontal-block"> 
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml(); ?> 
		</div>
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('deal-header')->toHtml(); ?> 
      </div>
	   </div>
    </div>
  </div>
 </div>