<?php
$brands = $this->getBrands();
$featured = $this->getFeaturedBrands();
$mediaUrl = $block->getMediaUrl();
?>

<style>
	.container-brand {
		display: flex;
		flex-wrap: wrap;
		justify-content: center;
  	}
	.container-brand .brand-wrapper:hover {
		transform: translateY(-10px);
		transition: 0.3s;
	}
	.container-brand .brand-img {
		width: 100px;
	}
</style>

<div class="page-title-wrapper">
	<h1 class="page-title" style="text-align:center" role="heading" aria-level="2"><?php echo __('Partner');?></h1>
</div>
<div class="container-brand" data-bind="scope: 'brandProducts'" data-role="brand-products-sidebar">
    	<?php foreach (range('0', '9') as $char) :?>
		<?php if(isset($brands[$char])):?>
				<?php foreach($brands[$char] as $_brand):?>
					<div class="brand-wrapper">					
					<?php if($_brand->getUrlKey()):?>
						<a href="<?php echo $this->getUrl('brand').$_brand->getUrlKey()?>"><!-- <?php //echo $_brand->getName();?> -->
							<img class="brand-img" src="<?php echo $mediaUrl.$_brand->getLogo() ?>" title="<?php echo $_brand->getName();?>" alt="<?php echo $_brand->getName();?>" />
						</a>
					<?php else:?>
						<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_brand->getId()));?>"><!-- <?php //echo $_brand->getName();?> -->
							<img class="brand-img" src="<?php echo $mediaUrl.$_brand->getLogo() ?>" title="<?php echo $_brand->getName();?>" alt="<?php echo $_brand->getName();?>" />
						</a>
					<?php endif;?>
					</div>
				<?php endforeach;?>		
		<?php endif;?>
	<?php endforeach;?>
	<?php  
	foreach (range('A', 'Z') as $char) :?>
		<?php if(isset($brands[$char])):?>
				<?php foreach($brands[$char] as $_brand):?>
					<div class="brand-wrapper">					
					<?php if($_brand->getUrlKey()):?>
						<a href="<?php echo $this->getUrl('brand').$_brand->getUrlKey()?>"><!-- <?php //echo $_brand->getName();?> -->
							<img class="brand-img" src="<?php echo $mediaUrl.$_brand->getLogo() ?>" title="<?php echo $_brand->getName();?>" alt="<?php echo $_brand->getName();?>" />
						</a>
					<?php else:?>
						<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_brand->getId()));?>"><!-- <?php //echo $_brand->getName();?> -->
						<img class="brand-img" src="<?php echo $mediaUrl.$_brand->getLogo() ?>" title="<?php echo $_brand->getName();?>" alt="<?php echo $_brand->getName();?>" />
						</a>
					<?php endif;?>
					</div>
				<?php endforeach;?>			
	<?php endif;?>
	<?php endforeach;?>
	
</div>