<?php 
$brands = $this->getFeaturedBrands();
$mediaUrl = $block->getMediaUrl();
?>
<div class="brand-home">
	<div class="brands-outer">
		<div class="brands-inner">
			<div class="column-inner">
				<div class="brand_title">
					<h2><?php echo __('Brand') ?></h2>
				</div>
				<div class="product-carousel brand-carousel" id="brand-carousel">
					<?php foreach($brands as $_brand):?>
						<div class="slider-item brand-item">
							<div class="product-block-inner">
								<?php if($_brand->getUrlKey()):?>
									<a href="<?php echo $this->getUrl('brand').$_brand->getUrlKey()?>">
								<?php else:?>
									<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_brand->getId()));?>">
								<?php endif;?>
								<?php if($_brand->getLogo()):?>
									<img class="brand-img" src="<?php echo $mediaUrl.$_brand->getLogo() ?>" title="<?php echo $_brand->getName();?>" alt="<?php echo $_brand->getName();?>" />
								<?php else:?>
								<span class="brand-title">
									<?php echo $_brand->getName();?>
								</span>
								<?php endif;?>
									</a>	
							</div>	
						</div>
					<?php endforeach;?>
				</div>
			</div>
		</div>
	</div>
</div>