<?php 
$brand = $this->getBrand();
$mediaUrl = $block->getMediaUrl();
$logo = $brand->getLogo();

echo '<p><strong>Media URL:</strong> ' . $mediaUrl . '</p>';
echo '<p><strong>Logo:</strong> ' . $logo . '</p>';
?>

<div class="page-title-wrapper">
	<h1 class="page-title">
		<span><?php echo $brand->getName();?></span>
	</h1>
</div>

<?php if ($brand->getLogo()): ?>
<div class="brand-image">
	<img class="brand-img" src="<?php echo $mediaUrl . $brand->getLogo(); ?>"
         title="<?php echo $block->escapeHtml($brand->getName()); ?>"
         alt="<?php echo $block->escapeHtml($brand->getName()); ?>" />
</div>
<?php endif; ?>

<div class="category-description">
    <?php echo $brand->getDescription();?>    
</div>

<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>